name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.26.3

      - name: Build
        run: go build ./...

      - name: Set up gotestsum
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Test
        run: |
          gotestsum --raw-command -- go test -json ./... --race

      - name: Validate Config
        run: go generate ./... && git diff --exit-code
