name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: go build ./...

      - name: Set up gotestsum
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Run tests with race detector
        run: |
          gotestsum -- -race ./...

      - name: Validate generated config
        run: |
          go generate ./...
          git diff --exit-code
